### ISSUE TITLE
hi.js Changes

### ISSUE THREAD

**Issue by BluZed** [mty22/krunker.io-translations#234] opened 2021-08-03 08:29 UTC
Working on hi.js

**Comment by BluZed** [comment] 2021-08-03 08:52
[here](https://github.com/mty22/krunker.io-translations/pull/235)
CHANGED VERY FEW THINGS

**Comment by mty22** [comment] 2021-08-11 10:34
please read the readme
duplicate of https://github.com/mty22/krunker.io-translations/issues/221

**Closed by mty22** 2021-08-11 10:34 UTC
