### ISSUE TITLE
Indonesian (B.Indo / Bahasa Indonesia) Translation

### ISSUE THREAD

**Issue by Thanosisnub** [mty22/krunker.io-translations#196] opened 2021-05-31 13:21 UTC

**Comment by Thanosisnub** [comment] 2021-05-31 13:22
pls approve:)

**Comment by mty22** [comment] 2021-06-01 13:11
Please.. please.. please.. read the README and use the search feature. 

Duplicate of https://github.com/mty22/krunker.io-translations/issues/105

**Closed by mty22** 2021-06-01 13:11 UTC
Labels: duplicate

**Comment by Thanosisnub** [comment] 2021-06-01 13:53
k read it...holding off bahasa....inform me pls when working on it
